### ISSUE TITLE
Error while running sweep of gbt

### ISSUE THREAD

**Issue by WuZheng326** [LeoGrin/tabular-benchmark#4]
Hi! I am following the readme file to re-run the trainning. I found that there is some bug while I running the wandb sweep agent. The bug is :
`Traceback (most recent call last):
  File "/home/wuzheng/.conda/envs/Hua/lib/python3.8/site-packages/wandb/wandb_agent.py", line 315, in _process_command
    result = self._command_run(command)
  File "/home/wuzheng/.conda/envs/Hua/lib/python3.8/site-packages/wandb/wandb_agent.py", line 425, in _command_run
    sweep_vars: Dict[str, Any] = Agent._create_command_args(command)
  File "/home/wuzheng/.conda/envs/Hua/lib/python3.8/site-packages/wandb/wandb_agent.py", line 358, in _create_command_args
    raise ValueError('No "value" found for command["args"]["%s"]' % param)
ValueError: No "value" found for command["args"]["model__max_leaf_nodes"]`

It seems like it is the bug from wandb, I guess if the version of wandb is wrong or it is the bug from python version. Could you please help me?

**Comment by LeoGrin** [comment]
Thanks for your feedback! This is related to an issue with recent versions of wandb (https://github.com/wandb/wandb/issues/4016). Using version 0.12.11 works. I've specified the right version on the requirements.txt.

**Comment by WuZheng326** [comment]
你好，我是吴峥，已收到您的邮件，我会尽快给您回复。
